// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comment (
    content, parent_id
) VALUES
(
    $1, $2
)
RETURNING id, content, parent_id, path, created_at
`

type CreateCommentParams struct {
	Content  string
	ParentID uuid.NullUUID
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Content, arg.ParentID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.ParentID,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comment
WHERE path LIKE concat($1::text, '%')
`

func (q *Queries) DeleteComment(ctx context.Context, dollar_1 string) error {
	_, err := q.db.ExecContext(ctx, deleteComment, dollar_1)
	return err
}

const getDerivatives = `-- name: GetDerivatives :many
SELECT id, content, parent_id, path, created_at FROM comment
WHERE path LIKE concat($1::text, '%')
`

func (q *Queries) GetDerivatives(ctx context.Context, dollar_1 string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getDerivatives, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.ParentID,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPathByCommentID = `-- name: GetPathByCommentID :one
SELECT path FROM comment
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPathByCommentID(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getPathByCommentID, id)
	var path sql.NullString
	err := row.Scan(&path)
	return path, err
}

const updateCommentPath = `-- name: UpdateCommentPath :exec
UPDATE comment
SET path = $1
WHERE id = $2
`

type UpdateCommentPathParams struct {
	Path sql.NullString
	ID   uuid.UUID
}

func (q *Queries) UpdateCommentPath(ctx context.Context, arg UpdateCommentPathParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentPath, arg.Path, arg.ID)
	return err
}
