// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID
	Content   string
	ParentID  uuid.NullUUID
	Path      sql.NullString
	CreatedAt sql.NullTime
}
