// Code generated by ent, DO NOT EDIT.

package click

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the click type in the database.
	Label = "click"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldClickedAt holds the string denoting the clicked_at field in the database.
	FieldClickedAt = "clicked_at"
	// EdgeLink holds the string denoting the link edge name in mutations.
	EdgeLink = "link"
	// Table holds the table name of the click in the database.
	Table = "clicks"
	// LinkTable is the table that holds the link relation/edge.
	LinkTable = "clicks"
	// LinkInverseTable is the table name for the Link entity.
	// It exists in this package in order to avoid circular dependency with the "link" package.
	LinkInverseTable = "links"
	// LinkColumn is the table column denoting the link relation/edge.
	LinkColumn = "link_clicks"
)

// Columns holds all SQL columns for click fields.
var Columns = []string{
	FieldID,
	FieldUserAgent,
	FieldIP,
	FieldClickedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "clicks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"link_clicks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Click queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByClickedAt orders the results by the clicked_at field.
func ByClickedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClickedAt, opts...).ToFunc()
}

// ByLinkField orders the results by link field.
func ByLinkField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinkStep(), sql.OrderByField(field, opts...))
	}
}
func newLinkStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinkInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LinkTable, LinkColumn),
	)
}
