// Code generated by ent, DO NOT EDIT.

package click

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Click {
	return predicate.Click(sql.FieldLTE(FieldID, id))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldUserAgent, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldIP, v))
}

// ClickedAt applies equality check predicate on the "clicked_at" field. It's identical to ClickedAtEQ.
func ClickedAt(v time.Time) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldClickedAt, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.Click {
	return predicate.Click(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.Click {
	return predicate.Click(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.Click {
	return predicate.Click(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.Click {
	return predicate.Click(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.Click {
	return predicate.Click(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.Click {
	return predicate.Click(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.Click {
	return predicate.Click(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.Click {
	return predicate.Click(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.Click {
	return predicate.Click(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.Click {
	return predicate.Click(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.Click {
	return predicate.Click(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.Click {
	return predicate.Click(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Click {
	return predicate.Click(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Click {
	return predicate.Click(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Click {
	return predicate.Click(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Click {
	return predicate.Click(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Click {
	return predicate.Click(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Click {
	return predicate.Click(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Click {
	return predicate.Click(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Click {
	return predicate.Click(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Click {
	return predicate.Click(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Click {
	return predicate.Click(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Click {
	return predicate.Click(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Click {
	return predicate.Click(sql.FieldContainsFold(FieldIP, v))
}

// ClickedAtEQ applies the EQ predicate on the "clicked_at" field.
func ClickedAtEQ(v time.Time) predicate.Click {
	return predicate.Click(sql.FieldEQ(FieldClickedAt, v))
}

// ClickedAtNEQ applies the NEQ predicate on the "clicked_at" field.
func ClickedAtNEQ(v time.Time) predicate.Click {
	return predicate.Click(sql.FieldNEQ(FieldClickedAt, v))
}

// ClickedAtIn applies the In predicate on the "clicked_at" field.
func ClickedAtIn(vs ...time.Time) predicate.Click {
	return predicate.Click(sql.FieldIn(FieldClickedAt, vs...))
}

// ClickedAtNotIn applies the NotIn predicate on the "clicked_at" field.
func ClickedAtNotIn(vs ...time.Time) predicate.Click {
	return predicate.Click(sql.FieldNotIn(FieldClickedAt, vs...))
}

// ClickedAtGT applies the GT predicate on the "clicked_at" field.
func ClickedAtGT(v time.Time) predicate.Click {
	return predicate.Click(sql.FieldGT(FieldClickedAt, v))
}

// ClickedAtGTE applies the GTE predicate on the "clicked_at" field.
func ClickedAtGTE(v time.Time) predicate.Click {
	return predicate.Click(sql.FieldGTE(FieldClickedAt, v))
}

// ClickedAtLT applies the LT predicate on the "clicked_at" field.
func ClickedAtLT(v time.Time) predicate.Click {
	return predicate.Click(sql.FieldLT(FieldClickedAt, v))
}

// ClickedAtLTE applies the LTE predicate on the "clicked_at" field.
func ClickedAtLTE(v time.Time) predicate.Click {
	return predicate.Click(sql.FieldLTE(FieldClickedAt, v))
}

// HasLink applies the HasEdge predicate on the "link" edge.
func HasLink() predicate.Click {
	return predicate.Click(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LinkTable, LinkColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinkWith applies the HasEdge predicate on the "link" edge with a given conditions (other predicates).
func HasLinkWith(preds ...predicate.Link) predicate.Click {
	return predicate.Click(func(s *sql.Selector) {
		step := newLinkStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Click) predicate.Click {
	return predicate.Click(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Click) predicate.Click {
	return predicate.Click(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Click) predicate.Click {
	return predicate.Click(sql.NotPredicates(p))
}
