// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/click"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/link"
)

// Click is the model entity for the Click schema.
type Click struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// ClickedAt holds the value of the "clicked_at" field.
	ClickedAt time.Time `json:"clicked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClickQuery when eager-loading is set.
	Edges        ClickEdges `json:"edges"`
	link_clicks  *int64
	selectValues sql.SelectValues
}

// ClickEdges holds the relations/edges for other nodes in the graph.
type ClickEdges struct {
	// Link holds the value of the link edge.
	Link *Link `json:"link,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LinkOrErr returns the Link value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClickEdges) LinkOrErr() (*Link, error) {
	if e.Link != nil {
		return e.Link, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: link.Label}
	}
	return nil, &NotLoadedError{edge: "link"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Click) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case click.FieldUserAgent, click.FieldIP:
			values[i] = new(sql.NullString)
		case click.FieldClickedAt:
			values[i] = new(sql.NullTime)
		case click.FieldID:
			values[i] = new(uuid.UUID)
		case click.ForeignKeys[0]: // link_clicks
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Click fields.
func (_m *Click) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case click.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case click.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case click.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case click.FieldClickedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field clicked_at", values[i])
			} else if value.Valid {
				_m.ClickedAt = value.Time
			}
		case click.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field link_clicks", value)
			} else if value.Valid {
				_m.link_clicks = new(int64)
				*_m.link_clicks = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Click.
// This includes values selected through modifiers, order, etc.
func (_m *Click) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLink queries the "link" edge of the Click entity.
func (_m *Click) QueryLink() *LinkQuery {
	return NewClickClient(_m.config).QueryLink(_m)
}

// Update returns a builder for updating this Click.
// Note that you need to call Click.Unwrap() before calling this method if this Click
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Click) Update() *ClickUpdateOne {
	return NewClickClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Click entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Click) Unwrap() *Click {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Click is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Click) String() string {
	var builder strings.Builder
	builder.WriteString("Click(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("clicked_at=")
	builder.WriteString(_m.ClickedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Clicks is a parsable slice of Click.
type Clicks []*Click
