// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/click"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/link"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/predicate"
)

// ClickUpdate is the builder for updating Click entities.
type ClickUpdate struct {
	config
	hooks    []Hook
	mutation *ClickMutation
}

// Where appends a list predicates to the ClickUpdate builder.
func (_u *ClickUpdate) Where(ps ...predicate.Click) *ClickUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *ClickUpdate) SetUserAgent(v string) *ClickUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ClickUpdate) SetNillableUserAgent(v *string) *ClickUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ClickUpdate) SetIP(v string) *ClickUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ClickUpdate) SetNillableIP(v *string) *ClickUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetClickedAt sets the "clicked_at" field.
func (_u *ClickUpdate) SetClickedAt(v time.Time) *ClickUpdate {
	_u.mutation.SetClickedAt(v)
	return _u
}

// SetNillableClickedAt sets the "clicked_at" field if the given value is not nil.
func (_u *ClickUpdate) SetNillableClickedAt(v *time.Time) *ClickUpdate {
	if v != nil {
		_u.SetClickedAt(*v)
	}
	return _u
}

// SetLinkID sets the "link" edge to the Link entity by ID.
func (_u *ClickUpdate) SetLinkID(id int64) *ClickUpdate {
	_u.mutation.SetLinkID(id)
	return _u
}

// SetNillableLinkID sets the "link" edge to the Link entity by ID if the given value is not nil.
func (_u *ClickUpdate) SetNillableLinkID(id *int64) *ClickUpdate {
	if id != nil {
		_u = _u.SetLinkID(*id)
	}
	return _u
}

// SetLink sets the "link" edge to the Link entity.
func (_u *ClickUpdate) SetLink(v *Link) *ClickUpdate {
	return _u.SetLinkID(v.ID)
}

// Mutation returns the ClickMutation object of the builder.
func (_u *ClickUpdate) Mutation() *ClickMutation {
	return _u.mutation
}

// ClearLink clears the "link" edge to the Link entity.
func (_u *ClickUpdate) ClearLink() *ClickUpdate {
	_u.mutation.ClearLink()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClickUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClickUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClickUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClickUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ClickUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(click.Table, click.Columns, sqlgraph.NewFieldSpec(click.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(click.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(click.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClickedAt(); ok {
		_spec.SetField(click.FieldClickedAt, field.TypeTime, value)
	}
	if _u.mutation.LinkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   click.LinkTable,
			Columns: []string{click.LinkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   click.LinkTable,
			Columns: []string{click.LinkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{click.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClickUpdateOne is the builder for updating a single Click entity.
type ClickUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClickMutation
}

// SetUserAgent sets the "user_agent" field.
func (_u *ClickUpdateOne) SetUserAgent(v string) *ClickUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *ClickUpdateOne) SetNillableUserAgent(v *string) *ClickUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *ClickUpdateOne) SetIP(v string) *ClickUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *ClickUpdateOne) SetNillableIP(v *string) *ClickUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetClickedAt sets the "clicked_at" field.
func (_u *ClickUpdateOne) SetClickedAt(v time.Time) *ClickUpdateOne {
	_u.mutation.SetClickedAt(v)
	return _u
}

// SetNillableClickedAt sets the "clicked_at" field if the given value is not nil.
func (_u *ClickUpdateOne) SetNillableClickedAt(v *time.Time) *ClickUpdateOne {
	if v != nil {
		_u.SetClickedAt(*v)
	}
	return _u
}

// SetLinkID sets the "link" edge to the Link entity by ID.
func (_u *ClickUpdateOne) SetLinkID(id int64) *ClickUpdateOne {
	_u.mutation.SetLinkID(id)
	return _u
}

// SetNillableLinkID sets the "link" edge to the Link entity by ID if the given value is not nil.
func (_u *ClickUpdateOne) SetNillableLinkID(id *int64) *ClickUpdateOne {
	if id != nil {
		_u = _u.SetLinkID(*id)
	}
	return _u
}

// SetLink sets the "link" edge to the Link entity.
func (_u *ClickUpdateOne) SetLink(v *Link) *ClickUpdateOne {
	return _u.SetLinkID(v.ID)
}

// Mutation returns the ClickMutation object of the builder.
func (_u *ClickUpdateOne) Mutation() *ClickMutation {
	return _u.mutation
}

// ClearLink clears the "link" edge to the Link entity.
func (_u *ClickUpdateOne) ClearLink() *ClickUpdateOne {
	_u.mutation.ClearLink()
	return _u
}

// Where appends a list predicates to the ClickUpdate builder.
func (_u *ClickUpdateOne) Where(ps ...predicate.Click) *ClickUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClickUpdateOne) Select(field string, fields ...string) *ClickUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Click entity.
func (_u *ClickUpdateOne) Save(ctx context.Context) (*Click, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClickUpdateOne) SaveX(ctx context.Context) *Click {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClickUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClickUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ClickUpdateOne) sqlSave(ctx context.Context) (_node *Click, err error) {
	_spec := sqlgraph.NewUpdateSpec(click.Table, click.Columns, sqlgraph.NewFieldSpec(click.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Click.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, click.FieldID)
		for _, f := range fields {
			if !click.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != click.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(click.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(click.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClickedAt(); ok {
		_spec.SetField(click.FieldClickedAt, field.TypeTime, value)
	}
	if _u.mutation.LinkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   click.LinkTable,
			Columns: []string{click.LinkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   click.LinkTable,
			Columns: []string{click.LinkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Click{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{click.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
