// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/click"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/link"
)

// ClickCreate is the builder for creating a Click entity.
type ClickCreate struct {
	config
	mutation *ClickMutation
	hooks    []Hook
}

// SetUserAgent sets the "user_agent" field.
func (_c *ClickCreate) SetUserAgent(v string) *ClickCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *ClickCreate) SetIP(v string) *ClickCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetClickedAt sets the "clicked_at" field.
func (_c *ClickCreate) SetClickedAt(v time.Time) *ClickCreate {
	_c.mutation.SetClickedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ClickCreate) SetID(v uuid.UUID) *ClickCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ClickCreate) SetNillableID(v *uuid.UUID) *ClickCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetLinkID sets the "link" edge to the Link entity by ID.
func (_c *ClickCreate) SetLinkID(id int64) *ClickCreate {
	_c.mutation.SetLinkID(id)
	return _c
}

// SetNillableLinkID sets the "link" edge to the Link entity by ID if the given value is not nil.
func (_c *ClickCreate) SetNillableLinkID(id *int64) *ClickCreate {
	if id != nil {
		_c = _c.SetLinkID(*id)
	}
	return _c
}

// SetLink sets the "link" edge to the Link entity.
func (_c *ClickCreate) SetLink(v *Link) *ClickCreate {
	return _c.SetLinkID(v.ID)
}

// Mutation returns the ClickMutation object of the builder.
func (_c *ClickCreate) Mutation() *ClickMutation {
	return _c.mutation
}

// Save creates the Click in the database.
func (_c *ClickCreate) Save(ctx context.Context) (*Click, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClickCreate) SaveX(ctx context.Context) *Click {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClickCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClickCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClickCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := click.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClickCreate) check() error {
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "Click.user_agent"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Click.ip"`)}
	}
	if _, ok := _c.mutation.ClickedAt(); !ok {
		return &ValidationError{Name: "clicked_at", err: errors.New(`ent: missing required field "Click.clicked_at"`)}
	}
	return nil
}

func (_c *ClickCreate) sqlSave(ctx context.Context) (*Click, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClickCreate) createSpec() (*Click, *sqlgraph.CreateSpec) {
	var (
		_node = &Click{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(click.Table, sqlgraph.NewFieldSpec(click.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(click.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(click.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.ClickedAt(); ok {
		_spec.SetField(click.FieldClickedAt, field.TypeTime, value)
		_node.ClickedAt = value
	}
	if nodes := _c.mutation.LinkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   click.LinkTable,
			Columns: []string{click.LinkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.link_clicks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClickCreateBulk is the builder for creating many Click entities in bulk.
type ClickCreateBulk struct {
	config
	err      error
	builders []*ClickCreate
}

// Save creates the Click entities in the database.
func (_c *ClickCreateBulk) Save(ctx context.Context) ([]*Click, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Click, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClickMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClickCreateBulk) SaveX(ctx context.Context) []*Click {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClickCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClickCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
