// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/click"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/link"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeClick = "Click"
	TypeLink  = "Link"
)

// ClickMutation represents an operation that mutates the Click nodes in the graph.
type ClickMutation struct {
	config
	op            Op
	typ           string
	id            *uuid.UUID
	user_agent    *string
	ip            *string
	clicked_at    *time.Time
	clearedFields map[string]struct{}
	link          *int64
	clearedlink   bool
	done          bool
	oldValue      func(context.Context) (*Click, error)
	predicates    []predicate.Click
}

var _ ent.Mutation = (*ClickMutation)(nil)

// clickOption allows management of the mutation configuration using functional options.
type clickOption func(*ClickMutation)

// newClickMutation creates new mutation for the Click entity.
func newClickMutation(c config, op Op, opts ...clickOption) *ClickMutation {
	m := &ClickMutation{
		config:        c,
		op:            op,
		typ:           TypeClick,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withClickID sets the ID field of the mutation.
func withClickID(id uuid.UUID) clickOption {
	return func(m *ClickMutation) {
		var (
			err   error
			once  sync.Once
			value *Click
		)
		m.oldValue = func(ctx context.Context) (*Click, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Click.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withClick sets the old Click of the mutation.
func withClick(node *Click) clickOption {
	return func(m *ClickMutation) {
		m.oldValue = func(context.Context) (*Click, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ClickMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ClickMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Click entities.
func (m *ClickMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ClickMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ClickMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Click.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserAgent sets the "user_agent" field.
func (m *ClickMutation) SetUserAgent(s string) {
	m.user_agent = &s
}

// UserAgent returns the value of the "user_agent" field in the mutation.
func (m *ClickMutation) UserAgent() (r string, exists bool) {
	v := m.user_agent
	if v == nil {
		return
	}
	return *v, true
}

// OldUserAgent returns the old "user_agent" field's value of the Click entity.
// If the Click object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClickMutation) OldUserAgent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserAgent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserAgent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserAgent: %w", err)
	}
	return oldValue.UserAgent, nil
}

// ResetUserAgent resets all changes to the "user_agent" field.
func (m *ClickMutation) ResetUserAgent() {
	m.user_agent = nil
}

// SetIP sets the "ip" field.
func (m *ClickMutation) SetIP(s string) {
	m.ip = &s
}

// IP returns the value of the "ip" field in the mutation.
func (m *ClickMutation) IP() (r string, exists bool) {
	v := m.ip
	if v == nil {
		return
	}
	return *v, true
}

// OldIP returns the old "ip" field's value of the Click entity.
// If the Click object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClickMutation) OldIP(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIP: %w", err)
	}
	return oldValue.IP, nil
}

// ResetIP resets all changes to the "ip" field.
func (m *ClickMutation) ResetIP() {
	m.ip = nil
}

// SetClickedAt sets the "clicked_at" field.
func (m *ClickMutation) SetClickedAt(t time.Time) {
	m.clicked_at = &t
}

// ClickedAt returns the value of the "clicked_at" field in the mutation.
func (m *ClickMutation) ClickedAt() (r time.Time, exists bool) {
	v := m.clicked_at
	if v == nil {
		return
	}
	return *v, true
}

// OldClickedAt returns the old "clicked_at" field's value of the Click entity.
// If the Click object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClickMutation) OldClickedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClickedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClickedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClickedAt: %w", err)
	}
	return oldValue.ClickedAt, nil
}

// ResetClickedAt resets all changes to the "clicked_at" field.
func (m *ClickMutation) ResetClickedAt() {
	m.clicked_at = nil
}

// SetLinkID sets the "link" edge to the Link entity by id.
func (m *ClickMutation) SetLinkID(id int64) {
	m.link = &id
}

// ClearLink clears the "link" edge to the Link entity.
func (m *ClickMutation) ClearLink() {
	m.clearedlink = true
}

// LinkCleared reports if the "link" edge to the Link entity was cleared.
func (m *ClickMutation) LinkCleared() bool {
	return m.clearedlink
}

// LinkID returns the "link" edge ID in the mutation.
func (m *ClickMutation) LinkID() (id int64, exists bool) {
	if m.link != nil {
		return *m.link, true
	}
	return
}

// LinkIDs returns the "link" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// LinkID instead. It exists only for internal usage by the builders.
func (m *ClickMutation) LinkIDs() (ids []int64) {
	if id := m.link; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetLink resets all changes to the "link" edge.
func (m *ClickMutation) ResetLink() {
	m.link = nil
	m.clearedlink = false
}

// Where appends a list predicates to the ClickMutation builder.
func (m *ClickMutation) Where(ps ...predicate.Click) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ClickMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ClickMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Click, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ClickMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ClickMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Click).
func (m *ClickMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ClickMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.user_agent != nil {
		fields = append(fields, click.FieldUserAgent)
	}
	if m.ip != nil {
		fields = append(fields, click.FieldIP)
	}
	if m.clicked_at != nil {
		fields = append(fields, click.FieldClickedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ClickMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case click.FieldUserAgent:
		return m.UserAgent()
	case click.FieldIP:
		return m.IP()
	case click.FieldClickedAt:
		return m.ClickedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ClickMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case click.FieldUserAgent:
		return m.OldUserAgent(ctx)
	case click.FieldIP:
		return m.OldIP(ctx)
	case click.FieldClickedAt:
		return m.OldClickedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Click field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ClickMutation) SetField(name string, value ent.Value) error {
	switch name {
	case click.FieldUserAgent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserAgent(v)
		return nil
	case click.FieldIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIP(v)
		return nil
	case click.FieldClickedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClickedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Click field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ClickMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ClickMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ClickMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Click numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ClickMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ClickMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ClickMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Click nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ClickMutation) ResetField(name string) error {
	switch name {
	case click.FieldUserAgent:
		m.ResetUserAgent()
		return nil
	case click.FieldIP:
		m.ResetIP()
		return nil
	case click.FieldClickedAt:
		m.ResetClickedAt()
		return nil
	}
	return fmt.Errorf("unknown Click field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ClickMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.link != nil {
		edges = append(edges, click.EdgeLink)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ClickMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case click.EdgeLink:
		if id := m.link; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ClickMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ClickMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ClickMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedlink {
		edges = append(edges, click.EdgeLink)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ClickMutation) EdgeCleared(name string) bool {
	switch name {
	case click.EdgeLink:
		return m.clearedlink
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ClickMutation) ClearEdge(name string) error {
	switch name {
	case click.EdgeLink:
		m.ClearLink()
		return nil
	}
	return fmt.Errorf("unknown Click unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ClickMutation) ResetEdge(name string) error {
	switch name {
	case click.EdgeLink:
		m.ResetLink()
		return nil
	}
	return fmt.Errorf("unknown Click edge %s", name)
}

// LinkMutation represents an operation that mutates the Link nodes in the graph.
type LinkMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	url           *string
	clearedFields map[string]struct{}
	clicks        map[uuid.UUID]struct{}
	removedclicks map[uuid.UUID]struct{}
	clearedclicks bool
	done          bool
	oldValue      func(context.Context) (*Link, error)
	predicates    []predicate.Link
}

var _ ent.Mutation = (*LinkMutation)(nil)

// linkOption allows management of the mutation configuration using functional options.
type linkOption func(*LinkMutation)

// newLinkMutation creates new mutation for the Link entity.
func newLinkMutation(c config, op Op, opts ...linkOption) *LinkMutation {
	m := &LinkMutation{
		config:        c,
		op:            op,
		typ:           TypeLink,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLinkID sets the ID field of the mutation.
func withLinkID(id int64) linkOption {
	return func(m *LinkMutation) {
		var (
			err   error
			once  sync.Once
			value *Link
		)
		m.oldValue = func(ctx context.Context) (*Link, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Link.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLink sets the old Link of the mutation.
func withLink(node *Link) linkOption {
	return func(m *LinkMutation) {
		m.oldValue = func(context.Context) (*Link, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LinkMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LinkMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Link entities.
func (m *LinkMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LinkMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LinkMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Link.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetURL sets the "url" field.
func (m *LinkMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *LinkMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the Link entity.
// If the Link object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LinkMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *LinkMutation) ResetURL() {
	m.url = nil
}

// AddClickIDs adds the "clicks" edge to the Click entity by ids.
func (m *LinkMutation) AddClickIDs(ids ...uuid.UUID) {
	if m.clicks == nil {
		m.clicks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.clicks[ids[i]] = struct{}{}
	}
}

// ClearClicks clears the "clicks" edge to the Click entity.
func (m *LinkMutation) ClearClicks() {
	m.clearedclicks = true
}

// ClicksCleared reports if the "clicks" edge to the Click entity was cleared.
func (m *LinkMutation) ClicksCleared() bool {
	return m.clearedclicks
}

// RemoveClickIDs removes the "clicks" edge to the Click entity by IDs.
func (m *LinkMutation) RemoveClickIDs(ids ...uuid.UUID) {
	if m.removedclicks == nil {
		m.removedclicks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.clicks, ids[i])
		m.removedclicks[ids[i]] = struct{}{}
	}
}

// RemovedClicks returns the removed IDs of the "clicks" edge to the Click entity.
func (m *LinkMutation) RemovedClicksIDs() (ids []uuid.UUID) {
	for id := range m.removedclicks {
		ids = append(ids, id)
	}
	return
}

// ClicksIDs returns the "clicks" edge IDs in the mutation.
func (m *LinkMutation) ClicksIDs() (ids []uuid.UUID) {
	for id := range m.clicks {
		ids = append(ids, id)
	}
	return
}

// ResetClicks resets all changes to the "clicks" edge.
func (m *LinkMutation) ResetClicks() {
	m.clicks = nil
	m.clearedclicks = false
	m.removedclicks = nil
}

// Where appends a list predicates to the LinkMutation builder.
func (m *LinkMutation) Where(ps ...predicate.Link) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LinkMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LinkMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Link, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LinkMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LinkMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Link).
func (m *LinkMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LinkMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.url != nil {
		fields = append(fields, link.FieldURL)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LinkMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case link.FieldURL:
		return m.URL()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LinkMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case link.FieldURL:
		return m.OldURL(ctx)
	}
	return nil, fmt.Errorf("unknown Link field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LinkMutation) SetField(name string, value ent.Value) error {
	switch name {
	case link.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	}
	return fmt.Errorf("unknown Link field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LinkMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LinkMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LinkMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Link numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LinkMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LinkMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LinkMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Link nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LinkMutation) ResetField(name string) error {
	switch name {
	case link.FieldURL:
		m.ResetURL()
		return nil
	}
	return fmt.Errorf("unknown Link field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LinkMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clicks != nil {
		edges = append(edges, link.EdgeClicks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LinkMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case link.EdgeClicks:
		ids := make([]ent.Value, 0, len(m.clicks))
		for id := range m.clicks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LinkMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedclicks != nil {
		edges = append(edges, link.EdgeClicks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LinkMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case link.EdgeClicks:
		ids := make([]ent.Value, 0, len(m.removedclicks))
		for id := range m.removedclicks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LinkMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedclicks {
		edges = append(edges, link.EdgeClicks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LinkMutation) EdgeCleared(name string) bool {
	switch name {
	case link.EdgeClicks:
		return m.clearedclicks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LinkMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Link unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LinkMutation) ResetEdge(name string) error {
	switch name {
	case link.EdgeClicks:
		m.ResetClicks()
		return nil
	}
	return fmt.Errorf("unknown Link edge %s", name)
}
