// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/ent/click"
	"github.com/misshanya/wb-tech-l3/url-shortener/internal/db/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	clickFields := schema.Click{}.Fields()
	_ = clickFields
	// clickDescID is the schema descriptor for id field.
	clickDescID := clickFields[0].Descriptor()
	// click.DefaultID holds the default value on creation for the id field.
	click.DefaultID = clickDescID.Default.(func() uuid.UUID)
}
