// Code generated by ent, DO NOT EDIT.

package link

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the link type in the database.
	Label = "link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// EdgeClicks holds the string denoting the clicks edge name in mutations.
	EdgeClicks = "clicks"
	// Table holds the table name of the link in the database.
	Table = "links"
	// ClicksTable is the table that holds the clicks relation/edge.
	ClicksTable = "clicks"
	// ClicksInverseTable is the table name for the Click entity.
	// It exists in this package in order to avoid circular dependency with the "click" package.
	ClicksInverseTable = "clicks"
	// ClicksColumn is the table column denoting the clicks relation/edge.
	ClicksColumn = "link_clicks"
)

// Columns holds all SQL columns for link fields.
var Columns = []string{
	FieldID,
	FieldURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Link queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByClicksCount orders the results by clicks count.
func ByClicksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClicksStep(), opts...)
	}
}

// ByClicks orders the results by clicks terms.
func ByClicks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClicksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newClicksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClicksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ClicksTable, ClicksColumn),
	)
}
