// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (original_filename) VALUES ($1::text)
RETURNING id, original_filename, status
`

func (q *Queries) CreateImage(ctx context.Context, filename string) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, filename)
	var i Image
	err := row.Scan(&i.ID, &i.OriginalFilename, &i.Status)
	return i, err
}

const getImage = `-- name: GetImage :one
SELECT id, original_filename, status FROM images
WHERE id = $1::uuid
`

func (q *Queries) GetImage(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(&i.ID, &i.OriginalFilename, &i.Status)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE images
SET
    status = $1::text
WHERE
    id = $2::uuid
`

type UpdateStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus, arg.Status, arg.ID)
	return err
}
