// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/misshanya/wb-tech-l3/delayed-notifier/internal/db/ent/notification"
	"github.com/misshanya/wb-tech-l3/delayed-notifier/internal/db/ent/predicate"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *NotificationUpdate) SetScheduledAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableScheduledAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NotificationUpdate) SetContent(v string) *NotificationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableContent(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *NotificationUpdate) SetChannel(v string) *NotificationUpdate {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableChannel(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetReceiver sets the "receiver" field.
func (_u *NotificationUpdate) SetReceiver(v string) *NotificationUpdate {
	_u.mutation.SetReceiver(v)
	return _u
}

// SetNillableReceiver sets the "receiver" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableReceiver(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetReceiver(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdate) SetStatus(v string) *NotificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableStatus(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := notification.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Notification.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := notification.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Notification.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Receiver(); ok {
		if err := notification.ReceiverValidator(v); err != nil {
			return &ValidationError{Name: "receiver", err: fmt.Errorf(`ent: validator failed for field "Notification.receiver": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(notification.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(notification.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Receiver(); ok {
		_spec.SetField(notification.FieldReceiver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *NotificationUpdateOne) SetScheduledAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableScheduledAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NotificationUpdateOne) SetContent(v string) *NotificationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableContent(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetChannel sets the "channel" field.
func (_u *NotificationUpdateOne) SetChannel(v string) *NotificationUpdateOne {
	_u.mutation.SetChannel(v)
	return _u
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableChannel(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetChannel(*v)
	}
	return _u
}

// SetReceiver sets the "receiver" field.
func (_u *NotificationUpdateOne) SetReceiver(v string) *NotificationUpdateOne {
	_u.mutation.SetReceiver(v)
	return _u
}

// SetNillableReceiver sets the "receiver" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableReceiver(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetReceiver(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationUpdateOne) SetStatus(v string) *NotificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableStatus(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := notification.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Notification.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Channel(); ok {
		if err := notification.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Notification.channel": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Receiver(); ok {
		if err := notification.ReceiverValidator(v); err != nil {
			return &ValidationError{Name: "receiver", err: fmt.Errorf(`ent: validator failed for field "Notification.receiver": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Notification.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(notification.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Channel(); ok {
		_spec.SetField(notification.FieldChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Receiver(); ok {
		_spec.SetField(notification.FieldReceiver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeString, value)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
