// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/misshanya/wb-tech-l3/delayed-notifier/internal/db/ent/notification"
	"github.com/misshanya/wb-tech-l3/delayed-notifier/internal/db/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescTitle is the schema descriptor for title field.
	notificationDescTitle := notificationFields[2].Descriptor()
	// notification.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	notification.TitleValidator = notificationDescTitle.Validators[0].(func(string) error)
	// notificationDescContent is the schema descriptor for content field.
	notificationDescContent := notificationFields[3].Descriptor()
	// notification.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	notification.ContentValidator = notificationDescContent.Validators[0].(func(string) error)
	// notificationDescChannel is the schema descriptor for channel field.
	notificationDescChannel := notificationFields[4].Descriptor()
	// notification.ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	notification.ChannelValidator = notificationDescChannel.Validators[0].(func(string) error)
	// notificationDescReceiver is the schema descriptor for receiver field.
	notificationDescReceiver := notificationFields[5].Descriptor()
	// notification.ReceiverValidator is a validator for the "receiver" field. It is called by the builders before save.
	notification.ReceiverValidator = notificationDescReceiver.Validators[0].(func(string) error)
	// notificationDescStatus is the schema descriptor for status field.
	notificationDescStatus := notificationFields[6].Descriptor()
	// notification.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	notification.StatusValidator = notificationDescStatus.Validators[0].(func(string) error)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
}
