// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Click is the predicate function for click builders.
type Click func(*sql.Selector)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)
