// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClicksColumns holds the columns for the "clicks" table.
	ClicksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_agent", Type: field.TypeString},
		{Name: "ip", Type: field.TypeString},
		{Name: "clicked_at", Type: field.TypeTime},
		{Name: "link_clicks", Type: field.TypeInt64, Nullable: true},
	}
	// ClicksTable holds the schema information for the "clicks" table.
	ClicksTable = &schema.Table{
		Name:       "clicks",
		Columns:    ClicksColumns,
		PrimaryKey: []*schema.Column{ClicksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "clicks_links_clicks",
				Columns:    []*schema.Column{ClicksColumns[4]},
				RefColumns: []*schema.Column{LinksColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LinksColumns holds the columns for the "links" table.
	LinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "url", Type: field.TypeString},
	}
	// LinksTable holds the schema information for the "links" table.
	LinksTable = &schema.Table{
		Name:       "links",
		Columns:    LinksColumns,
		PrimaryKey: []*schema.Column{LinksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClicksTable,
		LinksTable,
	}
)

func init() {
	ClicksTable.ForeignKeys[0].RefTable = LinksTable
}
